import IStrings from "./IStrings";

const EnglishStrings: IStrings = {
    // Messages
    MainHeading: "We come to you for the job!",
    BookAppointmentToday: "Book an appointment today!",
    ChooseADateAndTime: "Choose a date and time that works for you! Leave the work to us!",
    LearnMore: "Learn more about us!",
    WhatMakesUsGreat: "We are a team of individuals that get the job done everytime!",
    AboutUsContent: "At Mobile King Auto Shop, we believe car repair should be as convenient as possible. That's why we bring the mechanic shop to you. Whether you're at home, work, or stuck on the side of the road, our experienced team of certified mobile mechanics comes directly to your location, saving you the hassle of waiting in long lines or arranging for a tow.\n\nWe specialize in a wide range of services, from routine maintenance like oil changes and brake repairs to more complex engine diagnostics and fixes. With our fully-equipped mobile units, we can handle almost anything your vehicle needs-on the spot. We pride ourselves on providing top-notch service with a personal touch, ensuring that your car gets the care it deserves without interrupting your day.\n\nOur mission is simple: make car care easier, faster, and more affordable for you. Whether you're a busy professional, a parent juggling schedules, or simply someone who values their time, we're here to help you get back on the road-stress-free.",
    IsRequired: " is required",
    MustBeSameAs: " must be the same as ",
    NoServiceRequests: "No service requests exist",
    NoJobAssignments: "No job assignments exist",
    NoCreditCards: "No credit cards exist",
    NoPayments: "No payments exist",
    NoSpecialties: "No specialties exist",
    NoWorkDone: "No work done exits",
    NoInvoices: "No invoices exist",
    NoVehicles: "No vehicles exist",
    NoNotifications: "No notifications exist",
    NoUsers: "No users exist",
    NoUser: "No user exists",
    NoDataLoaded: "No data could be loaded",
    NewServiceRequestSuccess: "This service request was successfully submitted! You may view the status in the service requests section!",
    NewPaymentSuccess: "This payment was successfully made!",
    NewInvoiceSuccess: "This invoice was successfully made! The customer should see it now!",
    NewJobAssignmentSuccess: "This job assignment was successfully made! The technician should see it now!",
    NewTechnicianSpecialty: "This specialty was successfully made!",
    NewAccountSuccess: "This account was successfully created! You can login with it now!",
    NewWorkDoneSuccess: "This work was successfully created!",
    EditJobAssignmentSuccess: "This job assignment was successfully modified!",
    EditWorkDoneSuccess: "This work was successfully modified!",
    EditUserSuccess: "This user was successfully modified!",
    EditTechnicianSpecialtySuccess: "This specialty was successfully modified!",
    //Labels
    ChangeLanguage: "Change Language",
    AddServiceRequest: "Add Service Request",
    ServiceRequests: "Service Requests",
    Invoices: "Invoices",
    AboutUs: "About Us",
    Login: "Log in",
    Issue: "Issue Description",
    Make: "Make",
    Model: "Model",
    Year: "Year",
    Color: "Color",
    LicensePlate: "License Plate",
    VIN: "VIN",
    Vehicle: "Vehicle",
    Problem: "Problem",
    Location: "Location",
    Submit: "Submit",
    Cancel: "Cancelar",
    NewVehicle: "New Vehicle",
    Loading: "Loading",
    Password: "Password",
    Email: "Email",
    ForgotPassword: "Forgot password?",
    CreateAccount: "Create account?",
    ConfirmEmail: "Confirm Email",
    ConfirmPassword: "Confirm Password",
    FirstName: "First Name",
    LastName: "Last Name",
    PhoneNumber: "Phone Number",
    PersonalInformation: "Personal Information",
    ExistingVehicle: "Exisiting Vehicle",
    ID: "ID",
    Technician: "Technician",
    ServiceDate: "Service Date",
    WorkDone: "Work Done",
    Invoice: "Invoice",
    Gender: "Gender",
    OtherGender: "Other Gender",
    Welcome: "Welcome, ",
    Logout: "Logout",
    View: "View",
    Description: "Description",
    JobAssignment: "Job Assignment",
    Status: "Status",
    Amount: "Amount",
    DueDate: "Due Date",
    NewCard: "New Card",
    ExistingCard: "Existing Card",
    CreditCard: "Credit Card",
    Payment: "Payment",
    CardNumber: "Card Number",
    SecurityCode: "Security Code",
    ExpirationDate: "Expiration Date",
    Specialty: "Specialty",
    TechnicianSpecialty: "Technician Specialty",
    StartTime: "Start Time",
    EndTime: "End Time",
    Delete: "Delete",
    Edit: "Edit",
    AddWorkDone: "Add Work Done",
    Role: "Role",
    Users: "Users",
    AddTechnicianSpecialty: "Add Technician Specialty",
    User: "User",
    PayNow: "Pay Now",
    FullyPaid: "Fully Paid!"
}

export default EnglishStrings;