import IStrings from "./IStrings";

const SpanishStrings: IStrings = {
    // Messages
    MainHeading: "\u00A1Nosotros vengamos a usted para el trabajo!",
    BookAppointmentToday: "\u00A1Reserva una cita hoy!",
    ChooseADateAndTime: "\u00A1Elige una fecha y hora que funciona para usted! \u00A1Deja el trabajo a nosotros!",
    LearnMore: "\u00A1Aprende m\u00E1s sobre nosotros!",
    WhatMakesUsGreat: "\u00A1Nosotros somos un grupo de individuales que siempre hacemos el trabajo!",
    AboutUsContent: "En Mobile King Auto Shop, creemos que la reparaci\u00F3n de autos debe ser lo m\u00E1s conveniente posible. Por eso, llevamos el taller mec\u00E1nico directamente a ti. Ya sea en casa, en el trabajo o si te quedas varado en el camino, nuestro equipo de mec\u00E1nicos certificados llega directamente a tu ubicaci\u00F3n, ahorr\u00E1ndote la molestia de esperar en largas filas o de tener que organizar un remolque.\n\nNos especializamos en una amplia gama de servicios, desde mantenimiento rutinario como cambios de aceite y reparaci\u00F3n de frenos, hasta diagn\u00F3sticos complejos de motor y reparaciones. Con nuestras unidades m\u00F3viles totalmente equipadas, podemos encargarnos de casi cualquier cosa que tu veh\u00E1culo necesite, en el momento y en el lugar que lo necesites. Nos enorgullece ofrecer un servicio de alta calidad con un toque personal, asegur\u00E1ndonos de que tu auto reciba el cuidado que merece sin interrumpir tu d\u00EDa.\n\nNuestra misi\u00F3n es simple: hacer que el cuidado de tu veh\u00E1culo sea m\u00E1s f\u00E1cil, r\u00E1pido y accesible para ti. Ya seas un profesional ocupado, un padre o madre con una agenda apretada, o simplemente alguien que valora su tiempo, estamos aqu\u00E1 para ayudarte a volver a la carretera, sin estr\u00E9s.",
    IsRequired: " es necesario",
    MustBeSameAs: " must be the same as ",
    NoServiceRequests: "Solicitudes de servicios no existen",
    NoJobAssignments: "Encargos no existen",
    NoCreditCards: "Tarjetas de cr\u00E9dito no existen",
    NoInvoices: "Facturas no existen",
    NoPayments: "Pagos no existen",
    NoSpecialties: "Especialidades no existen",
    NoWorkDone: "Trabajo hecho no exista",
    NoVehicles: "Vehiculos no existen",
    NoNotifications: "Notificaciones no existen",
    NoUsers: "Usuarios no existen",
    NoUser: "Usuario no existe",
    NoDataLoaded: "Los datos no pueden cargarse",
    NewServiceRequestSuccess: "\u00A1Esta solicitud de servicio fue entregado exitosamente! \u00A1Puede ver el estado en la seccion de solicituds de servicios!",
    NewPaymentSuccess: "\u00A1Este pago fue creado exitosamente!",
    NewInvoiceSuccess: "\u00A1Esta factura fue creado exitosamente! \u00A1El client puede verlo ahora!",
    NewJobAssignmentSuccess: "\u00A1Este encargo fue creado exitosamente! El/La t\u00E9cnico/a puede verlo ahora!",
    NewTechnicianSpecialty: "\u00A1Esta especialidad fue creado exitosamente!",
    NewAccountSuccess: "\u00A1Esta cuenta fue creado exitosamente! Puedes iniciar la sesi\u00F3n con ella ahora!",
    NewWorkDoneSuccess: "\u00A1Este trabajo fue creado exitosamente!",
    EditJobAssignmentSuccess: "\u00A1Este encargo fue modificado exitosamente!",
    EditWorkDoneSuccess: "\u00A1Este trabajo fue modificado exitosamente!",
    EditUserSuccess: "\u00A1Este usuario fue modificado exitosamente!",
    EditTechnicianSpecialtySuccess: "\u00A1Esta especialidad fue modificado exitosamente!",
    //Labels
    ChangeLanguage: "Cambia Idioma",
    AddServiceRequest: "A\u00F1ada Solicitud de Serv\u00EDcio",
    ServiceRequests: "Solicitudes de servicios",
    Invoices: "Facturas",
    AboutUs: "Sobre nosotros",
    Login: "Iniciar Sesi\u00F3n",
    Issue: "Descripti\u00F3n del problema",
    Make: "Marca",
    Model: "Modelo",
    Year: "A\u00F1o",
    Color: "Color",
    LicensePlate: "Matr\u00EDcula",
    VIN: "VIN",
    Vehicle: "Veh\u00EDculo",
    Problem: "Problema",
    Location: "Ubicaci\u00F3n",
    Submit: "Entregar",
    Cancel: "Cancelar",
    NewVehicle: "Nuevo Veh\u00EDculo",
    Loading: "Cargando...",
    Password: "Contrase\u00F1a",
    Email: "Email",
    ForgotPassword: "\u00BFOlvida contrase\u00F1a?",
    CreateAccount: "\u00BFCrear cuenta?",
    ConfirmEmail: "Confirma Email",
    ConfirmPassword: "Confirma Contrase\u00F1a",
    FirstName: "Nombre",
    LastName: "Apellido",
    PhoneNumber: "Numero de Tel\u00E9fono",
    PersonalInformation: "Informaci\u00F1n Personal",
    ExistingVehicle: "Veh\u00EDculo Existente",
    ID: "ID",
    Technician: "T\u00E9cnico/a",
    ServiceDate: "Fecha de Servicio",
    WorkDone: "Trabajo hecho",
    Invoice: "Factura",
    Gender: "G\u00E9nero",
    OtherGender: "Otro G\u00E9nero",
    Welcome: "Bienvenidos, ",
    Logout: "Cerrar sesi\u00F3n",
    View: "Ver",
    Description: "Descripci\u00F3n",
    JobAssignment: "Encargo",
    Status: "Estado",
    Amount: "Cantidad",
    DueDate: "Fecha de Vencimiento",
    NewCard: "Nueva Tarjeta",
    ExistingCard: "Tarjeta Existente",
    CreditCard: "Tarjeta de Cr\u00E9dito",
    Payment: "Pago",
    CardNumber: "Numero de Tarjeta",
    SecurityCode: "C\u00F3digo de Seguridad",
    ExpirationDate: "Fecha de vencimiento",
    Specialty: "Especialidad",
    TechnicianSpecialty: "Especialidad de T\u00E9cnico/a",
    StartTime: "Tiempo de Comienzo",
    EndTime: "Tiempo de Fin",
    Delete: "Borrar",
    Edit: "Editar",
    AddWorkDone: "A\u00F1ada Trabajo",
    Role: "rol",
    Users: "Usuarios",
    AddTechnicianSpecialty: "A\u00F1ada Especialidad de T\u00E9cnico/a",
    User: "Usuario",
    PayNow: "Paga Ahora",
    FullyPaid: "\u00A1Pagado en Total!"
}

export default SpanishStrings;